/* tslint:disable */
/* eslint-disable */
/**
 * StoryVHandler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AudioUri
 */
export interface AudioUri {
    /**
     * 
     * @type {string}
     * @memberof AudioUri
     */
    original?: string;
    /**
     * 
     * @type {string}
     * @memberof AudioUri
     */
    mp3?: string;
    /**
     * 
     * @type {string}
     * @memberof AudioUri
     */
    webm?: string;
}

/**
 * Check if a given object implements the AudioUri interface.
 */
export function instanceOfAudioUri(value: object): value is AudioUri {
    return true;
}

export function AudioUriFromJSON(json: any): AudioUri {
    return AudioUriFromJSONTyped(json, false);
}

export function AudioUriFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioUri {
    if (json == null) {
        return json;
    }
    return {
        
        'original': json['original'] == null ? undefined : json['original'],
        'mp3': json['mp3'] == null ? undefined : json['mp3'],
        'webm': json['webm'] == null ? undefined : json['webm'],
    };
}

export function AudioUriToJSON(json: any): AudioUri {
    return AudioUriToJSONTyped(json, false);
}

export function AudioUriToJSONTyped(value?: AudioUri | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'original': value['original'],
        'mp3': value['mp3'],
        'webm': value['webm'],
    };
}

