/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthToken
 */
export interface AuthToken {
    /**
     * 
     * @type {number}
     * @memberof AuthToken
     */
    user_id?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthToken
     */
    access_token?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthToken
     */
    refresh_token?: string;
    /**
     * 
     * @type {number}
     * @memberof AuthToken
     */
    expires_at?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthToken
     */
    token_type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthToken
     */
    is_login?: boolean;
}

/**
 * Check if a given object implements the AuthToken interface.
 */
export function instanceOfAuthToken(value: object): value is AuthToken {
    return true;
}

export function AuthTokenFromJSON(json: any): AuthToken {
    return AuthTokenFromJSONTyped(json, false);
}

export function AuthTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthToken {
    if (json == null) {
        return json;
    }
    return {
        
        'user_id': json['user_id'] == null ? undefined : json['user_id'],
        'access_token': json['access_token'] == null ? undefined : json['access_token'],
        'refresh_token': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'expires_at': json['expires_at'] == null ? undefined : json['expires_at'],
        'token_type': json['token_type'] == null ? undefined : json['token_type'],
        'is_login': json['is_login'] == null ? undefined : json['is_login'],
    };
}

export function AuthTokenToJSON(json: any): AuthToken {
    return AuthTokenToJSONTyped(json, false);
}

export function AuthTokenToJSONTyped(value?: AuthToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['user_id'],
        'access_token': value['access_token'],
        'refresh_token': value['refresh_token'],
        'expires_at': value['expires_at'],
        'token_type': value['token_type'],
        'is_login': value['is_login'],
    };
}

