/* tslint:disable */
/* eslint-disable */
/**
 * StoryVHandler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseResp
 */
export interface BaseResp {
    /**
     * 
     * @type {number}
     * @memberof BaseResp
     */
    error_code?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResp
     */
    error_message?: string;
}

/**
 * Check if a given object implements the BaseResp interface.
 */
export function instanceOfBaseResp(value: object): value is BaseResp {
    return true;
}

export function BaseRespFromJSON(json: any): BaseResp {
    return BaseRespFromJSONTyped(json, false);
}

export function BaseRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResp {
    if (json == null) {
        return json;
    }
    return {
        
        'error_code': json['error_code'] == null ? undefined : json['error_code'],
        'error_message': json['error_message'] == null ? undefined : json['error_message'],
    };
}

export function BaseRespToJSON(json: any): BaseResp {
    return BaseRespToJSONTyped(json, false);
}

export function BaseRespToJSONTyped(value?: BaseResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error_code': value['error_code'],
        'error_message': value['error_message'],
    };
}

