/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Character
 */
export interface Character {
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    character_id?: number;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    character_avatar?: string;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    character_avatar_url?: string;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    intro?: string;
}

/**
 * Check if a given object implements the Character interface.
 */
export function instanceOfCharacter(value: object): value is Character {
    return true;
}

export function CharacterFromJSON(json: any): Character {
    return CharacterFromJSONTyped(json, false);
}

export function CharacterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Character {
    if (json == null) {
        return json;
    }
    return {
        
        'character_id': json['character_id'] == null ? undefined : json['character_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'character_avatar': json['character_avatar'] == null ? undefined : json['character_avatar'],
        'character_avatar_url': json['character_avatar_url'] == null ? undefined : json['character_avatar_url'],
        'intro': json['intro'] == null ? undefined : json['intro'],
    };
}

export function CharacterToJSON(json: any): Character {
    return CharacterToJSONTyped(json, false);
}

export function CharacterToJSONTyped(value?: Character | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'character_id': value['character_id'],
        'name': value['name'],
        'character_avatar': value['character_avatar'],
        'character_avatar_url': value['character_avatar_url'],
        'intro': value['intro'],
    };
}

