/* tslint:disable */
/* eslint-disable */
/**
 * StoryVHandler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EpisodeMessage } from './EpisodeMessage';
import {
    EpisodeMessageFromJSON,
    EpisodeMessageFromJSONTyped,
    EpisodeMessageToJSON,
    EpisodeMessageToJSONTyped,
} from './EpisodeMessage';

/**
 * 
 * @export
 * @interface Episode
 */
export interface Episode {
    /**
     * 
     * @type {number}
     * @memberof Episode
     */
    episode_id?: number;
    /**
     * 
     * @type {number}
     * @memberof Episode
     */
    story_id?: number;
    /**
     * 
     * @type {number}
     * @memberof Episode
     */
    index_of_story?: number;
    /**
     * 
     * @type {string}
     * @memberof Episode
     */
    cover_uri?: string;
    /**
     * 
     * @type {string}
     * @memberof Episode
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Episode
     */
    bio?: string;
    /**
     * 
     * @type {EpisodeMessage}
     * @memberof Episode
     */
    message_tree?: EpisodeMessage;
    /**
     * 
     * @type {number}
     * @memberof Episode
     */
    created_at?: number;
}

/**
 * Check if a given object implements the Episode interface.
 */
export function instanceOfEpisode(value: object): value is Episode {
    return true;
}

export function EpisodeFromJSON(json: any): Episode {
    return EpisodeFromJSONTyped(json, false);
}

export function EpisodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Episode {
    if (json == null) {
        return json;
    }
    return {
        
        'episode_id': json['episode_id'] == null ? undefined : json['episode_id'],
        'story_id': json['story_id'] == null ? undefined : json['story_id'],
        'index_of_story': json['index_of_story'] == null ? undefined : json['index_of_story'],
        'cover_uri': json['cover_uri'] == null ? undefined : json['cover_uri'],
        'title': json['title'] == null ? undefined : json['title'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'message_tree': json['message_tree'] == null ? undefined : EpisodeMessageFromJSON(json['message_tree']),
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
    };
}

export function EpisodeToJSON(json: any): Episode {
    return EpisodeToJSONTyped(json, false);
}

export function EpisodeToJSONTyped(value?: Episode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'episode_id': value['episode_id'],
        'story_id': value['story_id'],
        'index_of_story': value['index_of_story'],
        'cover_uri': value['cover_uri'],
        'title': value['title'],
        'bio': value['bio'],
        'message_tree': EpisodeMessageToJSON(value['message_tree']),
        'created_at': value['created_at'],
    };
}

