/* tslint:disable */
/* eslint-disable */
/**
 * StoryVHandler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseResp } from './BaseResp';
import {
    BaseRespFromJSON,
    BaseRespFromJSONTyped,
    BaseRespToJSON,
    BaseRespToJSONTyped,
} from './BaseResp';
import type { EpisodeMessage } from './EpisodeMessage';
import {
    EpisodeMessageFromJSON,
    EpisodeMessageFromJSONTyped,
    EpisodeMessageToJSON,
    EpisodeMessageToJSONTyped,
} from './EpisodeMessage';

/**
 * 
 * @export
 * @interface GetEpisodeMessagesResp
 */
export interface GetEpisodeMessagesResp {
    /**
     * 
     * @type {BaseResp}
     * @memberof GetEpisodeMessagesResp
     */
    baseResp?: BaseResp;
    /**
     * 
     * @type {string}
     * @memberof GetEpisodeMessagesResp
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof GetEpisodeMessagesResp
     */
    cover_uri?: string;
    /**
     * 
     * @type {number}
     * @memberof GetEpisodeMessagesResp
     */
    story_id?: number;
    /**
     * 
     * @type {number}
     * @memberof GetEpisodeMessagesResp
     */
    episode_id?: number;
    /**
     * 
     * @type {EpisodeMessage}
     * @memberof GetEpisodeMessagesResp
     */
    message?: EpisodeMessage;
}

/**
 * Check if a given object implements the GetEpisodeMessagesResp interface.
 */
export function instanceOfGetEpisodeMessagesResp(value: object): value is GetEpisodeMessagesResp {
    return true;
}

export function GetEpisodeMessagesRespFromJSON(json: any): GetEpisodeMessagesResp {
    return GetEpisodeMessagesRespFromJSONTyped(json, false);
}

export function GetEpisodeMessagesRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEpisodeMessagesResp {
    if (json == null) {
        return json;
    }
    return {
        
        'baseResp': json['baseResp'] == null ? undefined : BaseRespFromJSON(json['baseResp']),
        'title': json['title'] == null ? undefined : json['title'],
        'cover_uri': json['cover_uri'] == null ? undefined : json['cover_uri'],
        'story_id': json['story_id'] == null ? undefined : json['story_id'],
        'episode_id': json['episode_id'] == null ? undefined : json['episode_id'],
        'message': json['message'] == null ? undefined : EpisodeMessageFromJSON(json['message']),
    };
}

export function GetEpisodeMessagesRespToJSON(json: any): GetEpisodeMessagesResp {
    return GetEpisodeMessagesRespToJSONTyped(json, false);
}

export function GetEpisodeMessagesRespToJSONTyped(value?: GetEpisodeMessagesResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'baseResp': BaseRespToJSON(value['baseResp']),
        'title': value['title'],
        'cover_uri': value['cover_uri'],
        'story_id': value['story_id'],
        'episode_id': value['episode_id'],
        'message': EpisodeMessageToJSON(value['message']),
    };
}

