/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Episode } from './Episode';
import {
    EpisodeFromJSON,
    EpisodeFromJSONTyped,
    EpisodeToJSON,
    EpisodeToJSONTyped,
} from './Episode';
import type { Character } from './Character';
import {
    CharacterFromJSON,
    CharacterFromJSONTyped,
    CharacterToJSON,
    CharacterToJSONTyped,
} from './Character';

/**
 * 
 * @export
 * @interface ImportProofreadReq
 */
export interface ImportProofreadReq {
    /**
     * 
     * @type {string}
     * @memberof ImportProofreadReq
     */
    story_name?: string;
    /**
     * 
     * @type {string}
     * @memberof ImportProofreadReq
     */
    cover?: string;
    /**
     * 
     * @type {string}
     * @memberof ImportProofreadReq
     */
    bio?: string;
    /**
     * 
     * @type {Array<Character>}
     * @memberof ImportProofreadReq
     */
    character_list?: Array<Character>;
    /**
     * 
     * @type {Array<Episode>}
     * @memberof ImportProofreadReq
     */
    episode_list?: Array<Episode>;
}

/**
 * Check if a given object implements the ImportProofreadReq interface.
 */
export function instanceOfImportProofreadReq(value: object): value is ImportProofreadReq {
    return true;
}

export function ImportProofreadReqFromJSON(json: any): ImportProofreadReq {
    return ImportProofreadReqFromJSONTyped(json, false);
}

export function ImportProofreadReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportProofreadReq {
    if (json == null) {
        return json;
    }
    return {
        
        'story_name': json['story_name'] == null ? undefined : json['story_name'],
        'cover': json['cover'] == null ? undefined : json['cover'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'character_list': json['character_list'] == null ? undefined : ((json['character_list'] as Array<any>).map(CharacterFromJSON)),
        'episode_list': json['episode_list'] == null ? undefined : ((json['episode_list'] as Array<any>).map(EpisodeFromJSON)),
    };
}

export function ImportProofreadReqToJSON(json: any): ImportProofreadReq {
    return ImportProofreadReqToJSONTyped(json, false);
}

export function ImportProofreadReqToJSONTyped(value?: ImportProofreadReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'story_name': value['story_name'],
        'cover': value['cover'],
        'bio': value['bio'],
        'character_list': value['character_list'] == null ? undefined : ((value['character_list'] as Array<any>).map(CharacterToJSON)),
        'episode_list': value['episode_list'] == null ? undefined : ((value['episode_list'] as Array<any>).map(EpisodeToJSON)),
    };
}

