/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthToken } from './AuthToken';
import {
    AuthTokenFromJSON,
    AuthTokenFromJSONTyped,
    AuthTokenToJSON,
    AuthTokenToJSONTyped,
} from './AuthToken';

/**
 * 
 * @export
 * @interface LoginResp
 */
export interface LoginResp {
    /**
     * 
     * @type {AuthToken}
     * @memberof LoginResp
     */
    token?: AuthToken;
}

/**
 * Check if a given object implements the LoginResp interface.
 */
export function instanceOfLoginResp(value: object): value is LoginResp {
    return true;
}

export function LoginRespFromJSON(json: any): LoginResp {
    return LoginRespFromJSONTyped(json, false);
}

export function LoginRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResp {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : AuthTokenFromJSON(json['token']),
    };
}

export function LoginRespToJSON(json: any): LoginResp {
    return LoginRespToJSONTyped(json, false);
}

export function LoginRespToJSONTyped(value?: LoginResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': AuthTokenToJSON(value['token']),
    };
}

