/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginReq
 */
export interface LoginReq {
    /**
     * 
     * @type {string}
     * @memberof LoginReq
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginReq
     */
    password?: string;
}

/**
 * Check if a given object implements the LoginReq interface.
 */
export function instanceOfLoginReq(value: object): value is LoginReq {
    return true;
}

export function LoginReqFromJSON(json: any): LoginReq {
    return LoginReqFromJSONTyped(json, false);
}

export function LoginReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginReq {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function LoginReqToJSON(json: any): LoginReq {
    return LoginReqToJSONTyped(json, false);
}

export function LoginReqToJSONTyped(value?: LoginReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

