/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseResp } from './BaseResp';
import {
    BaseRespFromJSON,
    BaseRespFromJSONTyped,
    BaseRespToJSON,
    BaseRespToJSONTyped,
} from './BaseResp';

/**
 * 
 * @export
 * @interface LogoutResp
 */
export interface LogoutResp {
    /**
     * 
     * @type {BaseResp}
     * @memberof LogoutResp
     */
    baseResp?: BaseResp;
}

/**
 * Check if a given object implements the LogoutResp interface.
 */
export function instanceOfLogoutResp(value: object): value is LogoutResp {
    return true;
}

export function LogoutRespFromJSON(json: any): LogoutResp {
    return LogoutRespFromJSONTyped(json, false);
}

export function LogoutRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogoutResp {
    if (json == null) {
        return json;
    }
    return {
        
        'baseResp': json['baseResp'] == null ? undefined : BaseRespFromJSON(json['baseResp']),
    };
}

export function LogoutRespToJSON(json: any): LogoutResp {
    return LogoutRespToJSONTyped(json, false);
}

export function LogoutRespToJSONTyped(value?: LogoutResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'baseResp': BaseRespToJSON(value['baseResp']),
    };
}

