/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProofreadLoadEpisodeReq
 */
export interface ProofreadLoadEpisodeReq {
    /**
     * 
     * @type {number}
     * @memberof ProofreadLoadEpisodeReq
     */
    episode_id?: number;
}

/**
 * Check if a given object implements the ProofreadLoadEpisodeReq interface.
 */
export function instanceOfProofreadLoadEpisodeReq(value: object): value is ProofreadLoadEpisodeReq {
    return true;
}

export function ProofreadLoadEpisodeReqFromJSON(json: any): ProofreadLoadEpisodeReq {
    return ProofreadLoadEpisodeReqFromJSONTyped(json, false);
}

export function ProofreadLoadEpisodeReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProofreadLoadEpisodeReq {
    if (json == null) {
        return json;
    }
    return {
        
        'episode_id': json['episode_id'] == null ? undefined : json['episode_id'],
    };
}

export function ProofreadLoadEpisodeReqToJSON(json: any): ProofreadLoadEpisodeReq {
    return ProofreadLoadEpisodeReqToJSONTyped(json, false);
}

export function ProofreadLoadEpisodeReqToJSONTyped(value?: ProofreadLoadEpisodeReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'episode_id': value['episode_id'],
    };
}

