/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseResp } from './BaseResp';
import {
    BaseRespFromJSON,
    BaseRespFromJSONTyped,
    BaseRespToJSON,
    BaseRespToJSONTyped,
} from './BaseResp';

/**
 * 
 * @export
 * @interface ProofreadPostEpisodeResp
 */
export interface ProofreadPostEpisodeResp {
    /**
     * 
     * @type {BaseResp}
     * @memberof ProofreadPostEpisodeResp
     */
    baseResp?: BaseResp;
}

/**
 * Check if a given object implements the ProofreadPostEpisodeResp interface.
 */
export function instanceOfProofreadPostEpisodeResp(value: object): value is ProofreadPostEpisodeResp {
    return true;
}

export function ProofreadPostEpisodeRespFromJSON(json: any): ProofreadPostEpisodeResp {
    return ProofreadPostEpisodeRespFromJSONTyped(json, false);
}

export function ProofreadPostEpisodeRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProofreadPostEpisodeResp {
    if (json == null) {
        return json;
    }
    return {
        
        'baseResp': json['baseResp'] == null ? undefined : BaseRespFromJSON(json['baseResp']),
    };
}

export function ProofreadPostEpisodeRespToJSON(json: any): ProofreadPostEpisodeResp {
    return ProofreadPostEpisodeRespToJSONTyped(json, false);
}

export function ProofreadPostEpisodeRespToJSONTyped(value?: ProofreadPostEpisodeResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'baseResp': BaseRespToJSON(value['baseResp']),
    };
}

