/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Proofread
 */
export interface Proofread {
    /**
     * 
     * @type {number}
     * @memberof Proofread
     */
    cover_selection?: number;
    /**
     * 
     * @type {string}
     * @memberof Proofread
     */
    cover?: string;
    /**
     * 
     * @type {string}
     * @memberof Proofread
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof Proofread
     */
    comment?: string;
}

/**
 * Check if a given object implements the Proofread interface.
 */
export function instanceOfProofread(value: object): value is Proofread {
    return true;
}

export function ProofreadFromJSON(json: any): Proofread {
    return ProofreadFromJSONTyped(json, false);
}

export function ProofreadFromJSONTyped(json: any, ignoreDiscriminator: boolean): Proofread {
    if (json == null) {
        return json;
    }
    return {
        
        'cover_selection': json['cover_selection'] == null ? undefined : json['cover_selection'],
        'cover': json['cover'] == null ? undefined : json['cover'],
        'message': json['message'] == null ? undefined : json['message'],
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function ProofreadToJSON(json: any): Proofread {
    return ProofreadToJSONTyped(json, false);
}

export function ProofreadToJSONTyped(value?: Proofread | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cover_selection': value['cover_selection'],
        'cover': value['cover'],
        'message': value['message'],
        'comment': value['comment'],
    };
}

