/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseResp } from './BaseResp';
import {
    BaseRespFromJSON,
    BaseRespFromJSONTyped,
    BaseRespToJSON,
    BaseRespToJSONTyped,
} from './BaseResp';

/**
 * 
 * @export
 * @interface ProofreadUpdateMessageResp
 */
export interface ProofreadUpdateMessageResp {
    /**
     * 
     * @type {BaseResp}
     * @memberof ProofreadUpdateMessageResp
     */
    baseResp?: BaseResp;
}

/**
 * Check if a given object implements the ProofreadUpdateMessageResp interface.
 */
export function instanceOfProofreadUpdateMessageResp(value: object): value is ProofreadUpdateMessageResp {
    return true;
}

export function ProofreadUpdateMessageRespFromJSON(json: any): ProofreadUpdateMessageResp {
    return ProofreadUpdateMessageRespFromJSONTyped(json, false);
}

export function ProofreadUpdateMessageRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProofreadUpdateMessageResp {
    if (json == null) {
        return json;
    }
    return {
        
        'baseResp': json['baseResp'] == null ? undefined : BaseRespFromJSON(json['baseResp']),
    };
}

export function ProofreadUpdateMessageRespToJSON(json: any): ProofreadUpdateMessageResp {
    return ProofreadUpdateMessageRespToJSONTyped(json, false);
}

export function ProofreadUpdateMessageRespToJSONTyped(value?: ProofreadUpdateMessageResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'baseResp': BaseRespToJSON(value['baseResp']),
    };
}

