/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Proofread } from './Proofread';
import {
    ProofreadFromJSON,
    ProofreadFromJSONTyped,
    ProofreadToJSON,
    ProofreadToJSONTyped,
} from './Proofread';

/**
 * 
 * @export
 * @interface ProofreadCreateMessageReq
 */
export interface ProofreadCreateMessageReq {
    /**
     * 
     * @type {number}
     * @memberof ProofreadCreateMessageReq
     */
    episode_id?: number;
    /**
     * 
     * @type {number}
     * @memberof ProofreadCreateMessageReq
     */
    idx?: number;
    /**
     * 
     * @type {string}
     * @memberof ProofreadCreateMessageReq
     */
    subtitle?: string;
    /**
     * 
     * @type {number}
     * @memberof ProofreadCreateMessageReq
     */
    message_type?: number;
    /**
     * 
     * @type {string}
     * @memberof ProofreadCreateMessageReq
     */
    character?: string;
    /**
     * 
     * @type {string}
     * @memberof ProofreadCreateMessageReq
     */
    shot_description?: string;
    /**
     * 
     * @type {string}
     * @memberof ProofreadCreateMessageReq
     */
    tts?: string;
    /**
     * 
     * @type {number}
     * @memberof ProofreadCreateMessageReq
     */
    tts_duration?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProofreadCreateMessageReq
     */
    cover_list?: Array<string>;
    /**
     * 
     * @type {Proofread}
     * @memberof ProofreadCreateMessageReq
     */
    proofread?: Proofread;
}

/**
 * Check if a given object implements the ProofreadCreateMessageReq interface.
 */
export function instanceOfProofreadCreateMessageReq(value: object): value is ProofreadCreateMessageReq {
    return true;
}

export function ProofreadCreateMessageReqFromJSON(json: any): ProofreadCreateMessageReq {
    return ProofreadCreateMessageReqFromJSONTyped(json, false);
}

export function ProofreadCreateMessageReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProofreadCreateMessageReq {
    if (json == null) {
        return json;
    }
    return {
        
        'episode_id': json['episode_id'] == null ? undefined : json['episode_id'],
        'idx': json['idx'] == null ? undefined : json['idx'],
        'subtitle': json['subtitle'] == null ? undefined : json['subtitle'],
        'message_type': json['message_type'] == null ? undefined : json['message_type'],
        'character': json['character'] == null ? undefined : json['character'],
        'shot_description': json['shot_description'] == null ? undefined : json['shot_description'],
        'tts': json['tts'] == null ? undefined : json['tts'],
        'tts_duration': json['tts_duration'] == null ? undefined : json['tts_duration'],
        'cover_list': json['cover_list'] == null ? undefined : json['cover_list'],
        'proofread': json['proofread'] == null ? undefined : ProofreadFromJSON(json['proofread']),
    };
}

export function ProofreadCreateMessageReqToJSON(json: any): ProofreadCreateMessageReq {
    return ProofreadCreateMessageReqToJSONTyped(json, false);
}

export function ProofreadCreateMessageReqToJSONTyped(value?: ProofreadCreateMessageReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'episode_id': value['episode_id'],
        'idx': value['idx'],
        'subtitle': value['subtitle'],
        'message_type': value['message_type'],
        'character': value['character'],
        'shot_description': value['shot_description'],
        'tts': value['tts'],
        'tts_duration': value['tts_duration'],
        'cover_list': value['cover_list'],
        'proofread': ProofreadToJSON(value['proofread']),
    };
}

