/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseResp } from './BaseResp';
import {
    BaseRespFromJSON,
    BaseRespFromJSONTyped,
    BaseRespToJSON,
    BaseRespToJSONTyped,
} from './BaseResp';
import type { Story } from './Story';
import {
    StoryFromJSON,
    StoryFromJSONTyped,
    StoryToJSON,
    StoryToJSONTyped,
} from './Story';

/**
 * 
 * @export
 * @interface ProofreadLoadStoryResp
 */
export interface ProofreadLoadStoryResp {
    /**
     * 
     * @type {BaseResp}
     * @memberof ProofreadLoadStoryResp
     */
    baseResp?: BaseResp;
    /**
     * 
     * @type {Story}
     * @memberof ProofreadLoadStoryResp
     */
    story?: Story;
}

/**
 * Check if a given object implements the ProofreadLoadStoryResp interface.
 */
export function instanceOfProofreadLoadStoryResp(value: object): value is ProofreadLoadStoryResp {
    return true;
}

export function ProofreadLoadStoryRespFromJSON(json: any): ProofreadLoadStoryResp {
    return ProofreadLoadStoryRespFromJSONTyped(json, false);
}

export function ProofreadLoadStoryRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProofreadLoadStoryResp {
    if (json == null) {
        return json;
    }
    return {
        
        'baseResp': json['baseResp'] == null ? undefined : BaseRespFromJSON(json['baseResp']),
        'story': json['story'] == null ? undefined : StoryFromJSON(json['story']),
    };
}

export function ProofreadLoadStoryRespToJSON(json: any): ProofreadLoadStoryResp {
    return ProofreadLoadStoryRespToJSONTyped(json, false);
}

export function ProofreadLoadStoryRespToJSONTyped(value?: ProofreadLoadStoryResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'baseResp': BaseRespToJSON(value['baseResp']),
        'story': StoryToJSON(value['story']),
    };
}

