/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseResp } from './BaseResp';
import {
    BaseRespFromJSON,
    BaseRespFromJSONTyped,
    BaseRespToJSON,
    BaseRespToJSONTyped,
} from './BaseResp';

/**
 * 
 * @export
 * @interface ProofreadCreateMessageResp
 */
export interface ProofreadCreateMessageResp {
    /**
     * 
     * @type {BaseResp}
     * @memberof ProofreadCreateMessageResp
     */
    baseResp?: BaseResp;
    /**
     * 
     * @type {number}
     * @memberof ProofreadCreateMessageResp
     */
    message_id?: number;
}

/**
 * Check if a given object implements the ProofreadCreateMessageResp interface.
 */
export function instanceOfProofreadCreateMessageResp(value: object): value is ProofreadCreateMessageResp {
    return true;
}

export function ProofreadCreateMessageRespFromJSON(json: any): ProofreadCreateMessageResp {
    return ProofreadCreateMessageRespFromJSONTyped(json, false);
}

export function ProofreadCreateMessageRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProofreadCreateMessageResp {
    if (json == null) {
        return json;
    }
    return {
        
        'baseResp': json['baseResp'] == null ? undefined : BaseRespFromJSON(json['baseResp']),
        'message_id': json['message_id'] == null ? undefined : json['message_id'],
    };
}

export function ProofreadCreateMessageRespToJSON(json: any): ProofreadCreateMessageResp {
    return ProofreadCreateMessageRespToJSONTyped(json, false);
}

export function ProofreadCreateMessageRespToJSONTyped(value?: ProofreadCreateMessageResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'baseResp': BaseRespToJSON(value['baseResp']),
        'message_id': value['message_id'],
    };
}

