/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProofreadLoadStoryReq
 */
export interface ProofreadLoadStoryReq {
    /**
     * 
     * @type {number}
     * @memberof ProofreadLoadStoryReq
     */
    story_id?: number;
}

/**
 * Check if a given object implements the ProofreadLoadStoryReq interface.
 */
export function instanceOfProofreadLoadStoryReq(value: object): value is ProofreadLoadStoryReq {
    return true;
}

export function ProofreadLoadStoryReqFromJSON(json: any): ProofreadLoadStoryReq {
    return ProofreadLoadStoryReqFromJSONTyped(json, false);
}

export function ProofreadLoadStoryReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProofreadLoadStoryReq {
    if (json == null) {
        return json;
    }
    return {
        
        'story_id': json['story_id'] == null ? undefined : json['story_id'],
    };
}

export function ProofreadLoadStoryReqToJSON(json: any): ProofreadLoadStoryReq {
    return ProofreadLoadStoryReqToJSONTyped(json, false);
}

export function ProofreadLoadStoryReqToJSONTyped(value?: ProofreadLoadStoryReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'story_id': value['story_id'],
    };
}

