/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshReq
 */
export interface RefreshReq {
    /**
     * 
     * @type {string}
     * @memberof RefreshReq
     */
    refresh_token?: string;
}

/**
 * Check if a given object implements the RefreshReq interface.
 */
export function instanceOfRefreshReq(value: object): value is RefreshReq {
    return true;
}

export function RefreshReqFromJSON(json: any): RefreshReq {
    return RefreshReqFromJSONTyped(json, false);
}

export function RefreshReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshReq {
    if (json == null) {
        return json;
    }
    return {
        
        'refresh_token': json['refresh_token'] == null ? undefined : json['refresh_token'],
    };
}

export function RefreshReqToJSON(json: any): RefreshReq {
    return RefreshReqToJSONTyped(json, false);
}

export function RefreshReqToJSONTyped(value?: RefreshReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refresh_token': value['refresh_token'],
    };
}

