/* tslint:disable */
/* eslint-disable */
/**
 * StoryVHandler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoryTag
 */
export interface StoryTag {
    /**
     * 
     * @type {number}
     * @memberof StoryTag
     */
    tag_id?: number;
    /**
     * 
     * @type {string}
     * @memberof StoryTag
     */
    tag?: string;
}

/**
 * Check if a given object implements the StoryTag interface.
 */
export function instanceOfStoryTag(value: object): value is StoryTag {
    return true;
}

export function StoryTagFromJSON(json: any): StoryTag {
    return StoryTagFromJSONTyped(json, false);
}

export function StoryTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryTag {
    if (json == null) {
        return json;
    }
    return {
        
        'tag_id': json['tag_id'] == null ? undefined : json['tag_id'],
        'tag': json['tag'] == null ? undefined : json['tag'],
    };
}

export function StoryTagToJSON(json: any): StoryTag {
    return StoryTagToJSONTyped(json, false);
}

export function StoryTagToJSONTyped(value?: StoryTag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag_id': value['tag_id'],
        'tag': value['tag'],
    };
}

