/* tslint:disable */
/* eslint-disable */
/**
 * StoryVHandler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoryCounter
 */
export interface StoryCounter {
    /**
     * 
     * @type {number}
     * @memberof StoryCounter
     */
    story_id?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryCounter
     */
    user_view_count?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryCounter
     */
    user_continue_count?: number;
}

/**
 * Check if a given object implements the StoryCounter interface.
 */
export function instanceOfStoryCounter(value: object): value is StoryCounter {
    return true;
}

export function StoryCounterFromJSON(json: any): StoryCounter {
    return StoryCounterFromJSONTyped(json, false);
}

export function StoryCounterFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryCounter {
    if (json == null) {
        return json;
    }
    return {
        
        'story_id': json['story_id'] == null ? undefined : json['story_id'],
        'user_view_count': json['user_view_count'] == null ? undefined : json['user_view_count'],
        'user_continue_count': json['user_continue_count'] == null ? undefined : json['user_continue_count'],
    };
}

export function StoryCounterToJSON(json: any): StoryCounter {
    return StoryCounterToJSONTyped(json, false);
}

export function StoryCounterToJSONTyped(value?: StoryCounter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'story_id': value['story_id'],
        'user_view_count': value['user_view_count'],
        'user_continue_count': value['user_continue_count'],
    };
}

