/* tslint:disable */
/* eslint-disable */
/**
 * StoryVHandler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoryCharacter
 */
export interface StoryCharacter {
    /**
     * 
     * @type {number}
     * @memberof StoryCharacter
     */
    story_id?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryCharacter
     */
    character_id?: number;
    /**
     * 
     * @type {number}
     * @memberof StoryCharacter
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof StoryCharacter
     */
    character_name?: string;
    /**
     * 
     * @type {string}
     * @memberof StoryCharacter
     */
    character_avatar?: string;
    /**
     * 
     * @type {string}
     * @memberof StoryCharacter
     */
    intro?: string;
    /**
     * 
     * @type {number}
     * @memberof StoryCharacter
     */
    created_at?: number;
}

/**
 * Check if a given object implements the StoryCharacter interface.
 */
export function instanceOfStoryCharacter(value: object): value is StoryCharacter {
    return true;
}

export function StoryCharacterFromJSON(json: any): StoryCharacter {
    return StoryCharacterFromJSONTyped(json, false);
}

export function StoryCharacterFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryCharacter {
    if (json == null) {
        return json;
    }
    return {
        
        'story_id': json['story_id'] == null ? undefined : json['story_id'],
        'character_id': json['character_id'] == null ? undefined : json['character_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'character_name': json['character_name'] == null ? undefined : json['character_name'],
        'character_avatar': json['character_avatar'] == null ? undefined : json['character_avatar'],
        'intro': json['intro'] == null ? undefined : json['intro'],
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
    };
}

export function StoryCharacterToJSON(json: any): StoryCharacter {
    return StoryCharacterToJSONTyped(json, false);
}

export function StoryCharacterToJSONTyped(value?: StoryCharacter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'story_id': value['story_id'],
        'character_id': value['character_id'],
        'status': value['status'],
        'character_name': value['character_name'],
        'character_avatar': value['character_avatar'],
        'intro': value['intro'],
        'created_at': value['created_at'],
    };
}

