/* tslint:disable */
/* eslint-disable */
/**
 * StoryVHandler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseResp } from './BaseResp';
import {
    BaseRespFromJSON,
    BaseRespFromJSONTyped,
    BaseRespToJSON,
    BaseRespToJSONTyped,
} from './BaseResp';

/**
 * 
 * @export
 * @interface UserActionLogResp
 */
export interface UserActionLogResp {
    /**
     * 
     * @type {BaseResp}
     * @memberof UserActionLogResp
     */
    baseResp?: BaseResp;
}

/**
 * Check if a given object implements the UserActionLogResp interface.
 */
export function instanceOfUserActionLogResp(value: object): value is UserActionLogResp {
    return true;
}

export function UserActionLogRespFromJSON(json: any): UserActionLogResp {
    return UserActionLogRespFromJSONTyped(json, false);
}

export function UserActionLogRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserActionLogResp {
    if (json == null) {
        return json;
    }
    return {
        
        'baseResp': json['baseResp'] == null ? undefined : BaseRespFromJSON(json['baseResp']),
    };
}

export function UserActionLogRespToJSON(json: any): UserActionLogResp {
    return UserActionLogRespToJSONTyped(json, false);
}

export function UserActionLogRespToJSONTyped(value?: UserActionLogResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'baseResp': BaseRespToJSON(value['baseResp']),
    };
}

