/* tslint:disable */
/* eslint-disable */
/**
 * StoryVHandler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserActionExperiment
 */
export interface UserActionExperiment {
    /**
     * 
     * @type {string}
     * @memberof UserActionExperiment
     */
    experiment_id?: string;
    /**
     * 
     * @type {number}
     * @memberof UserActionExperiment
     */
    variation_id?: number;
}

/**
 * Check if a given object implements the UserActionExperiment interface.
 */
export function instanceOfUserActionExperiment(value: object): value is UserActionExperiment {
    return true;
}

export function UserActionExperimentFromJSON(json: any): UserActionExperiment {
    return UserActionExperimentFromJSONTyped(json, false);
}

export function UserActionExperimentFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserActionExperiment {
    if (json == null) {
        return json;
    }
    return {
        
        'experiment_id': json['experiment_id'] == null ? undefined : json['experiment_id'],
        'variation_id': json['variation_id'] == null ? undefined : json['variation_id'],
    };
}

export function UserActionExperimentToJSON(json: any): UserActionExperiment {
    return UserActionExperimentToJSONTyped(json, false);
}

export function UserActionExperimentToJSONTyped(value?: UserActionExperiment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'experiment_id': value['experiment_id'],
        'variation_id': value['variation_id'],
    };
}

