/* tslint:disable */
/* eslint-disable */
/**
 * StoryVHandler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserActionLog } from './UserActionLog';
import {
    UserActionLogFromJSON,
    UserActionLogFromJSONTyped,
    UserActionLogToJSON,
    UserActionLogToJSONTyped,
} from './UserActionLog';

/**
 * 
 * @export
 * @interface UserActionLogReq
 */
export interface UserActionLogReq {
    /**
     * 
     * @type {Array<UserActionLog>}
     * @memberof UserActionLogReq
     */
    logs?: Array<UserActionLog>;
}

/**
 * Check if a given object implements the UserActionLogReq interface.
 */
export function instanceOfUserActionLogReq(value: object): value is UserActionLogReq {
    return true;
}

export function UserActionLogReqFromJSON(json: any): UserActionLogReq {
    return UserActionLogReqFromJSONTyped(json, false);
}

export function UserActionLogReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserActionLogReq {
    if (json == null) {
        return json;
    }
    return {
        
        'logs': json['logs'] == null ? undefined : ((json['logs'] as Array<any>).map(UserActionLogFromJSON)),
    };
}

export function UserActionLogReqToJSON(json: any): UserActionLogReq {
    return UserActionLogReqToJSONTyped(json, false);
}

export function UserActionLogReqToJSONTyped(value?: UserActionLogReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logs': value['logs'] == null ? undefined : ((value['logs'] as Array<any>).map(UserActionLogToJSON)),
    };
}

