/* tslint:disable */
/* eslint-disable */
/**
 * StoryVHandler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserActionExperiment } from './UserActionExperiment';
import {
    UserActionExperimentFromJSON,
    UserActionExperimentFromJSONTyped,
    UserActionExperimentToJSON,
    UserActionExperimentToJSONTyped,
} from './UserActionExperiment';

/**
 * 
 * @export
 * @interface UserActionLog
 */
export interface UserActionLog {
    /**
     * 
     * @type {string}
     * @memberof UserActionLog
     */
    client_uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof UserActionLog
     */
    user_id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserActionLog
     */
    app_version?: string;
    /**
     * 
     * @type {number}
     * @memberof UserActionLog
     */
    local_time?: number;
    /**
     * event related
     * @type {number}
     * @memberof UserActionLog
     */
    event_type?: number;
    /**
     * 
     * @type {string}
     * @memberof UserActionLog
     */
    event_name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserActionLog
     */
    parameters?: string;
    /**
     * device related
     * @type {string}
     * @memberof UserActionLog
     */
    device_id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserActionLog
     */
    idfv?: string;
    /**
     * 
     * @type {string}
     * @memberof UserActionLog
     */
    android_id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserActionLog
     */
    platform?: string;
    /**
     * 
     * @type {string}
     * @memberof UserActionLog
     */
    os_type?: string;
    /**
     * 
     * @type {string}
     * @memberof UserActionLog
     */
    os_version?: string;
    /**
     * 
     * @type {string}
     * @memberof UserActionLog
     */
    device_model?: string;
    /**
     * 
     * @type {string}
     * @memberof UserActionLog
     */
    brand_name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserActionLog
     */
    install_id?: string;
    /**
     * 
     * @type {number}
     * @memberof UserActionLog
     */
    calibrate_id?: number;
    /**
     * experiments bound to this action
     * @type {Array<UserActionExperiment>}
     * @memberof UserActionLog
     */
    experiments?: Array<UserActionExperiment>;
    /**
     * 
     * @type {string}
     * @memberof UserActionLog
     */
    request_ip?: string;
}

/**
 * Check if a given object implements the UserActionLog interface.
 */
export function instanceOfUserActionLog(value: object): value is UserActionLog {
    return true;
}

export function UserActionLogFromJSON(json: any): UserActionLog {
    return UserActionLogFromJSONTyped(json, false);
}

export function UserActionLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserActionLog {
    if (json == null) {
        return json;
    }
    return {
        
        'client_uuid': json['client_uuid'] == null ? undefined : json['client_uuid'],
        'user_id': json['user_id'] == null ? undefined : json['user_id'],
        'app_version': json['app_version'] == null ? undefined : json['app_version'],
        'local_time': json['local_time'] == null ? undefined : json['local_time'],
        'event_type': json['event_type'] == null ? undefined : json['event_type'],
        'event_name': json['event_name'] == null ? undefined : json['event_name'],
        'parameters': json['parameters'] == null ? undefined : json['parameters'],
        'device_id': json['device_id'] == null ? undefined : json['device_id'],
        'idfv': json['idfv'] == null ? undefined : json['idfv'],
        'android_id': json['android_id'] == null ? undefined : json['android_id'],
        'platform': json['platform'] == null ? undefined : json['platform'],
        'os_type': json['os_type'] == null ? undefined : json['os_type'],
        'os_version': json['os_version'] == null ? undefined : json['os_version'],
        'device_model': json['device_model'] == null ? undefined : json['device_model'],
        'brand_name': json['brand_name'] == null ? undefined : json['brand_name'],
        'install_id': json['install_id'] == null ? undefined : json['install_id'],
        'calibrate_id': json['calibrate_id'] == null ? undefined : json['calibrate_id'],
        'experiments': json['experiments'] == null ? undefined : ((json['experiments'] as Array<any>).map(UserActionExperimentFromJSON)),
        'request_ip': json['request_ip'] == null ? undefined : json['request_ip'],
    };
}

export function UserActionLogToJSON(json: any): UserActionLog {
    return UserActionLogToJSONTyped(json, false);
}

export function UserActionLogToJSONTyped(value?: UserActionLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_uuid': value['client_uuid'],
        'user_id': value['user_id'],
        'app_version': value['app_version'],
        'local_time': value['local_time'],
        'event_type': value['event_type'],
        'event_name': value['event_name'],
        'parameters': value['parameters'],
        'device_id': value['device_id'],
        'idfv': value['idfv'],
        'android_id': value['android_id'],
        'platform': value['platform'],
        'os_type': value['os_type'],
        'os_version': value['os_version'],
        'device_model': value['device_model'],
        'brand_name': value['brand_name'],
        'install_id': value['install_id'],
        'calibrate_id': value['calibrate_id'],
        'experiments': value['experiments'] == null ? undefined : ((value['experiments'] as Array<any>).map(UserActionExperimentToJSON)),
        'request_ip': value['request_ip'],
    };
}

